default: &default
  peaks:
    count: 2304
    quality: 0.5
  specs: 
    - format: webm
      audio: 
        bitrate: 96
      video: false
      options: 
        - "-dash 1"
      extension: webm
    - format: mp3
      audio:
        bitrate: 128
      video: false
      extension: mp3
  metadata:
    platform: juke
  client:
    endpoint: http://localhost:3002
    max_attempts: 1
  function: ffmpeg-dev-transcode
  host: http://docker.for.mac.localhost:3000

development:
  <<: *default


test:
  <<: *default
  peaks:
    count: 576
    quality: 0.5
  specs: 
    - format: webm
      audio: 
        bitrate: 96
      video: false
      options: 
        - "-dash 1"
      extension: webm
  host: http://localhost:3000

production:
  <<: *default
  client: {}
  function: ffmpeg-dev-transcode
  host: <%= ENV['HOST'] %>
