default: &default
  specs: [
    {
      format: webm,
      bitrate: 96,
      options: ['-dash 1']
    },
    {
      format: aac,
      bitrate: 96
    },
    {
      format: mp3,
      bitrate: 64
    }
  ]
  metadata: {
    platform: noisepuff
  }
  client: {
    endpoint: http://localhost:3001,
    ssl_verify_peer: false,
    max_attempts: 1
  }

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
  client: null
