source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.7.2'


gem 'rails', '~> 6.1.0'
gem 'pg', '>= 0.18', '< 2.0'
gem 'puma', '~> 4.1'

gem 'rack-cors'
gem 'jbuilder', '~> 2.7'
gem 'friendly_id'
gem 'scenic'
gem 'jwt'
gem 'bootsnap', '>= 1.4.2', require: false

gem 'aws-sdk-s3', require: false
gem 'aws-sdk-lambda', require: false

gem 'image_processing', '~> 1.2'
gem 'bcrypt'
gem 'device_detector'
# gem 'geocoder'

# gems that are in main group so Heroku loads them
gem 'factory_bot_rails'
gem 'faker'
gem 'ruby-audioinfo', require: 'audioinfo'
gem 'mime-types', require: 'mime/types'
gem 'pry-rails'

group :development, :test do
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
  gem 'rspec-rails'
end

group :development do
  gem 'listen', '~> 3.2'
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
  gem 'spring-commands-rspec'
  gem 'guard-rspec'
  gem 'better_errors'
  gem 'binding_of_caller'
  gem 'annotate'
  gem 'mailcatcher'
  gem 'letter_opener'
end

group :test do
  gem 'shoulda-matchers'
  gem 'launchy'
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
# gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
