# frozen_string_literal: true

source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.7.2'

gem 'pg', '>= 0.18', '< 2.0'
gem 'puma', '~> 4.1'
gem 'rails', '~> 6.1.0'

gem 'bootsnap', '>= 1.4.2', require: false
gem 'friendly_id'
gem 'jbuilder', '~> 2.7'
gem 'jwt'
gem 'rack-cors'
gem 'scenic'

gem 'aws-sdk-lambda', require: false
gem 'aws-sdk-s3', require: false

gem 'bcrypt'
gem 'device_detector'
gem 'image_processing', '~> 1.2'
# gem 'geocoder'

# gems that are in main group so Heroku loads them
gem 'factory_bot_rails'
gem 'faker'
gem 'mime-types', require: 'mime/types'
gem 'pry-rails'
gem 'ruby-audioinfo', require: 'audioinfo'

group :development, :test do
  gem 'byebug', platforms: %i[mri mingw x64_mingw]
  gem 'dotenv-rails'
  gem 'rspec-rails'
end

group :development do
  gem 'annotate'
  gem 'better_errors'
  gem 'binding_of_caller'
  gem 'guard-rspec'
  gem 'letter_opener'
  gem 'listen', '~> 3.2'
  gem 'mailcatcher'
  gem 'rubocop', require: false
  gem 'rubocop-rails', require: false
  gem 'spring'
  gem 'spring-commands-rspec'
  gem 'spring-watcher-listen', '~> 2.0.0'
end

group :test do
  gem 'launchy'
  gem 'shoulda-matchers'
  gem 'webmock'
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
# gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
